dependencies = []
description = "Terraform provider for managing OUTSCALE resources"
destination_server = []
flags = ["devops", "sdk", "tools"]
owner = "team-infrastructure-engineering@scalingo.com"
team = "IET"
version = "1.1.4"
tier = 1
